@echo off
mkdir "backend\app\db\migrations" 2>nul
mkdir "backend\app\services" 2>nul
mkdir "backend\tests" 2>nul
mkdir "frontend" 2>nul
mkdir "frontend\src" 2>nul
mkdir "frontend\src\pages" 2>nul
mkdir "frontend\src\components" 2>nul
mkdir "frontend\src\services" 2>nul
mkdir "frontend\src\context" 2>nul
mkdir "docs" 2>nul
mkdir "scripts" 2>nul

echo. > "backend\app\api\auth.py"
echo. > "backend\app\api\tp.py"
echo. > "backend\app\api\vm.py"
echo. > "backend\app\api\guacamole.py"
echo. > "backend\app\core\security.py"
echo. > "backend\app\db\models.py"
echo. > "backend\app\services\cas_service.py"
echo. > "backend\app\services\proxmox_service.py"
echo. > "backend\app\services\guacamole_service.py"
echo. > "backend\requirements.txt"
echo. > "frontend\src\pages\LoginPage.jsx"
echo. > "frontend\src\pages\DashboardPage.jsx"
echo. > "frontend\src\pages\LabPage.jsx"
echo. > "frontend\src\pages\AdminPage.jsx"
echo. > "frontend\src\components\VMList.jsx"
echo. > "frontend\src\components\TPForm.jsx"
echo. > "frontend\src\components\GuacamoleClient.jsx"
echo. > "frontend\src\services\api.js"
echo. > "frontend\src\context\AuthContext.js"
echo. > "frontend\src\App.jsx"
echo. > "frontend\package.json"
echo. > "frontend\Dockerfile"
echo. > "frontend\.env.example"
echo. > "docs\ARCHITECTURE.md"
echo. > "docs\INSTALLATION.md"
echo. > "docs\API.md"
echo. > "docs\CAS_INTEGRATION.md"
echo. > "scripts\init-db.sql"
echo. > "scripts\mock-cas.py"
echo. > "scripts\setup.sh"
echo. > ".env.example"
