// src/components/GuacamoleDisplay.jsx
// This component expects a full Guacamole URL (including /#/client/...)
// Prefer passing a `connectionUrl` prop generated by the backend.
const GuacamoleDisplay = ({ connectionUrl, connectionToken }) => {
  const GUAC_BASE = process.env.REACT_APP_GUAC_BASE || 'http://localhost:8088/guacamole';
  const url = connectionUrl || (connectionToken ? `${GUAC_BASE}/#/client/${connectionToken}` : '');

  return (
    <div className="w-full h-[80vh] border-2 border-gray-800 rounded-lg overflow-hidden">
      {url ? (
        <iframe
          src={url}
          width="100%"
          height="100%"
          title="VM Display"
          allowFullScreen
        />
      ) : (
        <div className="p-4">No Guacamole URL provided</div>
      )}
    </div>
  );
};

export default GuacamoleDisplay;